import type { Listing } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    _id: '1',
    ownerId: {
      _id: '101',
      name: 'Sunny Day',
      avatar: 'https://placehold.co/40x40.png'
    },
    listingName: 'Sunshine Residences',
    propertyType: 'Apartment',
    description: 'Great place, very clean and accessible!',
    rating: 5,
    photos: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png'
    ],
    fullAddress: '123 Mabini St, Cabanatuan City',
    lat: 15.4849,
    lng: 120.9619,
    roomType: 'Solo Room',
    availableRooms: 3,
    bedrooms: '1',
    bathrooms: '1',
    squareFeet: 12,
    monthlyRent: 3500,
    moveInDate: '2024-06-01',
    securityDeposit: 3500,
    advancePayment: 3500,
    applicationReviewFee: 0,
    specialtyProperty: 'None',
    petPolicy: 'No Pets',
    hasEnhancedViewing: false,
    hasCurfew: false,
    visitorsAllowed: true,
    smokingAllowed: false,
    cookingAllowed: true,
    quietHours: '10 PM',
    airConditioning: false,
    wifi: true,
    washer: false,
    dryer: false,
    utilitiesIncluded: true,
    dishwasher: false,
    parkingType: 'None',
    laundryFacilities: false,
    kitchen: true,
    appliancesIncluded: false,
    status: 'Active',
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2024-05-20T15:30:00Z',
    floorPlans: [],
    neighborhoodNear: ['University'],
    transportationOptions: ['Jeepney'],
  },
  {
    id: '2',
    _id: '2',
    ownerId: {
      _id: '102',
      name: 'Maria Maple',
      avatar: 'https://placehold.co/40x40.png'
    },
    listingName: 'Maple Tree Dormitory',
    propertyType: 'Boarding House',
    description: 'Perfect for students, near the university.',
    rating: 4,
    photos: [
      'https://placehold.co/600x400.png',
      'https://placehold.co/600x400.png'
    ],
    fullAddress: '456 Burgos Ave, Cabanatuan City',
    lat: 15.4941,
    lng: 120.9723,
    roomType: 'Bed Spacer',
    availableRooms: 5,
    bedrooms: 'Studio',
    bathrooms: '2',
    squareFeet: 10,
    monthlyRent: 2500,
    moveInDate: '2024-06-01',
    securityDeposit: 2500,
    advancePayment: 2500,
    applicationReviewFee: 0,
    specialtyProperty: 'Student Only',
    petPolicy: 'No Pets',
    hasEnhancedViewing: false,
    hasCurfew: true,
    visitorsAllowed: true,
    smokingAllowed: false,
    cookingAllowed: false,
    quietHours: '11 PM',
    airConditioning: false,
    wifi: true,
    washer: false,
    dryer: false,
    utilitiesIncluded: true,
    dishwasher: false,
    parkingType: 'None',
    laundryFacilities: true,
    kitchen: false,
    appliancesIncluded: false,
    status: 'Active',
    createdAt: '2023-11-15T12:00:00Z',
    updatedAt: '2024-05-18T11:00:00Z',
    floorPlans: [],
    neighborhoodNear: ['University'],
    transportationOptions: ['Jeepney'],
  }
];

export const featuredListings = listings.slice(0, 2);
